# see https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for docs

# MD004 - Unordered list style
# We want to use dashes consistently everywhere
MD004:
  style: dash

# MD007 - Unordered list indentation
# We want to prevent conflict between the muliple apps involved to modify markdown
MD007:
  indent: 4

# MD013 - Line length
# We do not want to artificially limit line length in a language like markdown because of the nature of the language's handling of whitespace.  Line wrapping is just a fact of life in markdown and trying to impose the conventions of other languages on markdown is an impedance mismatch that leads to people thinking that whitespace in markdown is more representative of the rendered HTML than it really is.
MD013: false

# MD033 - Inline HTML
MD033:
  allowed_elements:
    - details # there is no markdown equivalent for accordions
    - summary # there is no markdown equivalent for accordions
    - br
