local c = require('thescream.palette')

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()

    -- highlights
    hl(0, "Normal", { fg = c.fg, bg = c.bg })
    hl(0, "SignColumn", {  bg = c.bg })
    hl(0, "MsgArea", { fg = c.fg, bg = c.bg })
    hl(0, "ModeMsg", { fg = c.fg, bg = c.black })
    hl(0, "MsgSeparator", { fg = c.fg, bg = c.bg })
    hl(0, "SpellBad", { underline = true, italic = true,  })
    hl(0, "SpellCap", { fg = c.yellow, underline = true, })
    hl(0, "SpellLocal", { fg = c.green, underline = true, })
    hl(0, "SpellRare", { fg = c.purple, underline = true, })
    hl(0, "NormalNC", { fg = c.fg, bg = c.bg })
    hl(0, "Pmenu", { fg = c.dark_grey, bg = c.light_grey, sp = 'NONE', blend = 50, })
    hl(0, "PmenuSel", {  bg = c.blue })
    hl(0, "WildMenu", { fg = c.fg, bg = c.blue })
    hl(0, "CursorLineNr", { fg = c.dark_grey, bold = true, })
    hl(0, "Comment", { fg = c.grey, italic = true, })
    hl(0, "Folded", { fg = c.dark_grey, bg = c.alt_bg })
    hl(0, "FoldColumn", { fg = c.dark_grey, bg = c.alt_bg })
    hl(0, "LineNr", { fg = c.grey, })
    hl(0, "Whitespace", { fg = c.bg, })
    hl(0, "VertSplit", { fg = c.grey, bg = c.bg })
    hl(0, "CursorLine", {  bg = c.black })
    hl(0, "CursorColumn", {  bg = c.black })
    hl(0, "ColorColumn", {  bg = c.black })
    hl(0, "NormalFloat", {  bg = c.bg })
    hl(0, "FloatBorder", {  bg = c.alt_bg })
    hl(0, "FloatTitle", {  bg = c.alt_bg })
    hl(0, "Visual", {  bg = c.blue })
    hl(0, "VisualNOS", {  bg = c.alt_bg })
    hl(0, "WarningMsg", { fg = c.red, bg = c.bg })
    hl(0, "DiffAdd", { fg = c.alt_bg, bg = c.add })
    hl(0, "DiffChange", { fg = c.alt_bg, bg = c.change, underline = true, })
    hl(0, "DiffDelete", { fg = c.alt_bg, bg = c.delete })
    hl(0, "QuickFixLine", {  bg = c.blue })
    hl(0, "PmenuSbar", { bg = c.alt_bg })
    hl(0, "PmenuThumb", { bg = c.grey })
    hl(0, "MatchWord", { underline = true, })
    hl(0, "MatchParen", { fg = c.blue, bg = c.bg, underline = true, })
    hl(0, "MatchWordCur", { underline = true, })
    hl(0, "MatchParenCur", { underline = true, })
    hl(0, "Cursor", { fg = c.dark_grey, bg = c.grey })
    hl(0, "lCursor", { fg = c.dark_grey, bg = c.grey })
    hl(0, "CursorIM", { fg = c.dark_grey, bg = c.grey })
    hl(0, "TermCursor", { fg = c.dark_grey, bg = c.grey })
    hl(0, "TermCursorNC", { fg = c.dark_grey, bg = c.grey })
    hl(0, "Conceal", { fg = c.dark_grey, })
    hl(0, "Directory", { fg = c.blue, })
    hl(0, "SpecialKey", { fg = c.blue, bold = true, })
    hl(0, "Title", { fg = c.blue, bold = true, })
    hl(0, "ErrorMsg", { fg = c.red, bg = c.bg, bold = true, })
    hl(0, "Search", { fg = c.dark_grey, bg = c.blue })
    hl(0, "IncSearch", { fg = c.orange, bg = c.dark_grey })
    hl(0, "Substitute", { fg = c.dark_grey, bg = c.orange })
    hl(0, "MoreMsg", { fg = c.orange, })
    hl(0, "Question", { fg = c.orange, })
    hl(0, "EndOfBuffer", { fg = c.bg, })
    hl(0, "NonText", { fg = c.bg, })
    hl(0, "Variable", { fg = c.light_blue, })
    hl(0, "String", { fg = c.orange, })
    hl(0, "Character", { fg = c.orange, })
    hl(0, "Constant", { fg = c.light_blue, })
    hl(0, "Number", { fg = c.light_green, })
    hl(0, "Boolean", { fg = c.blue, })
    hl(0, "Float", { fg = c.light_green, })
    hl(0, "Identifier", { fg = c.light_blue, })
    hl(0, "Function", { fg = c.yellow, })
    hl(0, "Operator", { fg = c.fg, })
    hl(0, "Type", { fg = c.light_blue, })
    hl(0, "StorageClass", { fg = c.blue, })
    hl(0, "Structure", { fg = c.blue, })
    hl(0, "Typedef", { fg = c.blue, })
    hl(0, "Keyword", { fg = c.blue, })
    hl(0, "Statement", { fg = c.purple, })
    hl(0, "Conditional", { fg = c.blue, })
    hl(0, "Repeat", { fg = c.purple, })
    hl(0, "Label", { fg = c.purple, })
    hl(0, "Exception", { fg = c.purple, })
    hl(0, "Include", { fg = c.purple, })
    hl(0, "PreProc", { fg = c.purple, })
    hl(0, "Define", { fg = c.purple, })
    hl(0, "Macro", { fg = c.purple, })
    hl(0, "PreCondit", { fg = c.purple, })
    hl(0, "Special", { fg = c.orange, })
    hl(0, "SpecialChar", { fg = c.white, })
    hl(0, "Tag", { fg = c.blue, })
    hl(0, "Debug", { fg = c.red, })
    hl(0, "Delimiter", { fg = c.grey, })
    hl(0, "SpecialComment", { fg = c.grey, })
    hl(0, "Underlined", { underline = true, })
    hl(0, "Bold", { bold = true, })
    hl(0, "Italic", { italic = true, })
    hl(0, "Ignore", { fg = c.light_blue, bg = c.bg, bold = true, })
    hl(0, "Todo", { fg = c.light_purple, bg = c.bg, bold = true, })
    hl(0, "Error", { fg = c.red, bg = c.bg, bold = true, })
    hl(0, "TabLine", { fg = c.dark_grey, bg = c.light_grey })
    hl(0, "TabLineSel", { fg = c.white, bg = c.light_grey })
    hl(0, "TabLineFill", { fg = c.light_grey, bg = c.light_grey })

    -- Treesitter
    hl(0, "TSComment", { link = 'Comment' })
    hl(0, "TSAnnotation", { fg = c.blue, })
    hl(0, "TSAttribute", { fg = c.light_blue, })
    hl(0, "TSConstructor", { fg = c.light_blue, })
    hl(0, "TSType", { fg = c.light_blue, })
    hl(0, "TSTypeBuiltin", { fg = c.orange, })
    hl(0, "TSConditional", { fg = c.yellow, })
    hl(0, "TSException", { fg = c.purple, })
    hl(0, "TSInclude", { fg = c.purple, })
    hl(0, "TSKeywordReturn", { fg = c.purple, })
    hl(0, "TSKeyword", { fg = c.purple, })
    hl(0, "TSKeywordFunction", { fg = c.purple, })
    hl(0, "TSLabel", { fg = c.light_blue, })
    hl(0, "TSNamespace", { fg = c.light_blue, })
    hl(0, "TSRepeat", { fg = c.yellow, })
    hl(0, "TSConstant", { fg = c.orange, })
    hl(0, "TSConstBuiltin", { fg = c.orange, })
    hl(0, "TSFloat", { fg = c.orange, })
    hl(0, "TSNumber", { fg = c.orange, })
    hl(0, "TSBoolean", { fg = c.orange, })
    hl(0, "TSCharacter", { fg = c.green, })
    hl(0, "TSError", { fg = c.red, })
    hl(0, "TSFunction", { fg = c.blue, })
    hl(0, "TSFuncBuiltin", { fg = c.blue, })
    hl(0, "TSMethod", { fg = c.blue, })
    hl(0, "TSConstMacro", { fg = c.orange, })
    hl(0, "TSFuncMacro", { fg = c.blue, })
    hl(0, "TSVariable", { fg = c.light_blue, })
    hl(0, "TSVariableBuiltin", { fg = c.red, })
    hl(0, "TSProperty", { fg = c.red, })
    hl(0, "TSField", { fg = c.fg, })
    hl(0, "TSParameter", { fg = c.red, })
    hl(0, "TSParameterReference", { fg = c.red, })
    hl(0, "TSSymbol", { fg = c.light_blue, })
    hl(0, "TSText", { fg = c.alt_fg, })
    hl(0, "TSOperator", { fg = c.alt_fg, })
    hl(0, "TSPunctDelimiter", { fg = c.alt_fg, })
    hl(0, "TSTagDelimiter", { fg = c.alt_fg, })
    hl(0, "TSTagAttribute", { fg = c.orange, })
    hl(0, "TSPunctBracket", { fg = c.alt_fg, })
    hl(0, "TSPunctSpecial", { fg = c.purple, })
    hl(0, "TSString", { fg = c.green, })
    hl(0, "TSStringRegex", { fg = c.green, })
    hl(0, "TSStringEscape", { fg = c.green, })
    hl(0, "TSTag", { fg = c.blue, })
    hl(0, "TSEmphasis", { italic = true, })
    hl(0, "TSUnderline", { underline = true, })
    hl(0, "TSTitle", { fg = c.fg, })
    hl(0, "TSLiteral", { fg = c.orange, })
    hl(0, "TSURI", { fg = c.orange, underline = true, })
    hl(0, "TSKeywordOperator", { fg = c.purple, })
    hl(0, "TSStructure", { fg = c.light_blue, })
    hl(0, "TSStrong", { fg = c.blue, bold = true, })
    hl(0, "TSQueryLinterError", { fg = c.orange, })
    hl(0, "TreesitterContext", { bg = c.black })

    -- markdown
    hl(0, "markdownBlockquote", { fg = c.green, })
    hl(0, "markdownCode", { fg = c.orange, })
    hl(0, "markdownCodeBlock", { fg = c.orange, })
    hl(0, "markdownCodeDelimiter", { fg = c.orange, })
    hl(0, "markdownH1", { fg = c.blue, })
    hl(0, "markdownH2", { fg = c.blue, })
    hl(0, "markdownH3", { fg = c.blue, })
    hl(0, "markdownH4", { fg = c.blue, })
    hl(0, "markdownH5", { fg = c.blue, })
    hl(0, "markdownH6", { fg = c.blue, })
    hl(0, "markdownHeadingDelimiter", { fg = c.blue, })
    hl(0, "markdownHeadingRule", { fg = c.fg, bold = true, })
    hl(0, "markdownId", { fg = c.purple, })
    hl(0, "markdownIdDeclaration", { fg = c.blue, })
    hl(0, "markdownIdDelimiter", { fg = c.dark_grey, })
    hl(0, "markdownLinkDelimiter", { fg = c.dark_grey, })
    hl(0, "markdownBold", { fg = c.blue, bold = true, })
    hl(0, "markdownItalic", { italic = true, })
    hl(0, "markdownBoldItalic", { fg = c.yellow, bold = true, italic = true, })
    hl(0, "markdownListMarker", { fg = c.blue, })
    hl(0, "markdownOrderedListMarker", { fg = c.blue, })
    hl(0, "markdownRule", { fg = c.dark_grey, })
    hl(0, "markdownUrl", { fg = c.light_blue, underline = true, })
    hl(0, "markdownLinkText", { fg = c.blue, })
    hl(0, "markdownFootnote", { fg = c.orange, })
    hl(0, "markdownFootnoteDefinition", { fg = c.orange, })
    hl(0, "markdownEscape", { fg = c.yellow, })

    -- Whichkey
    hl(0, "WhichKey", { fg = c.orange, })
    hl(0, "WhichKeySeparator", { fg = c.green, })
    hl(0, "WhichKeyGroup", { fg = c.blue, })
    hl(0, "WhichKeyDesc", { fg = c.light_blue, })
    hl(0, "WhichKeyFloat", { bg = c.black })

    -- Git
    hl(0, "SignAdd", { fg = c.add, })
    hl(0, "SignChange", { fg = c.change, })
    hl(0, "SignDelete", { fg = c.delete, })
    hl(0, "GitSignsAdd", { fg = c.add, })
    hl(0, "GitSignsChange", { fg = c.change, })
    hl(0, "GitSignsDelete", { fg = c.delete, })

    -- LSP
    hl(0, "LspDiagnosticsDefaultError", { fg = c.red, })
    hl(0, "LspDiagnosticsDefaultWarning", { fg = c.orange, })
    hl(0, "LspDiagnosticsDefaultInformation", { fg = c.yellow, })
    hl(0, "LspDiagnosticsDefaultInfo", { fg = c.yellow, })
    hl(0, "LspDiagnosticsDefaultHint", { fg = c.blue, })
    hl(0, "LspDiagnosticsVirtualTextError", { fg = c.red, })
    hl(0, "LspDiagnosticsVirtualTextWarning", { fg = c.orange, })
    hl(0, "LspDiagnosticsVirtualTextInformation", { fg = c.yellow, })
    hl(0, "LspDiagnosticsVirtualTextInfo", { fg = c.yellow, })
    hl(0, "LspDiagnosticsVirtualTextHint", { fg = c.blue, })
    hl(0, "LspDiagnosticsFloatingError", { fg = c.red, })
    hl(0, "LspDiagnosticsFloatingWarning", { fg = c.orange, })
    hl(0, "LspDiagnosticsFloatingInformation", { fg = c.yellow, })
    hl(0, "LspDiagnosticsFloatingInfo", { fg = c.yellow, })
    hl(0, "LspDiagnosticsFloatingHint", { fg = c.blue, })
    hl(0, "DiagnosticSignError", { fg = c.red, })
    hl(0, "DiagnosticSignWarning", { fg = c.orange, })
    hl(0, "DiagnosticSignInformation", { fg = c.yellow, })
    hl(0, "DiagnosticSignInfo", { fg = c.yellow, })
    hl(0, "DiagnosticSignHint", { fg = c.blue, })
    hl(0, "LspDiagnosticsSignError", { fg = c.red, })
    hl(0, "LspDiagnosticsSignWarning", { fg = c.orange, })
    hl(0, "LspDiagnosticsSignInformation", { fg = c.yellow, })
    hl(0, "LspDiagnosticsSignInfo", { fg = c.yellow, })
    hl(0, "LspDiagnosticsSignHint", { fg = c.blue, })
    hl(0, "LspDiagnosticsError", { fg = c.red, })
    hl(0, "LspDiagnosticsWarning", { fg = c.orange, })
    hl(0, "LspDiagnosticsInformation", { fg = c.yellow, })
    hl(0, "LspDiagnosticsInfo", { fg = c.yellow, })
    hl(0, "LspDiagnosticsHint", { fg = c.blue, })
    hl(0, "LspDiagnosticsUnderlineError", { underline = true, })
    hl(0, "LspDiagnosticsUnderlineWarning", { underline = true, })
    hl(0, "LspDiagnosticsUnderlineInformation", { underline = true, })
    hl(0, "LspDiagnosticsUnderlineInfo", { underline = true, })
    hl(0, "LspDiagnosticsUnderlineHint", { underline = true, })
    hl(0, "LspReferenceRead", {  })
    hl(0, "LspReferenceText", {  })
    hl(0, "LspReferenceWrite", {  })
    hl(0, "LspCodeLens", { fg = c.grey, italic = true, })
    hl(0, "LspCodeLensSeparator", { fg = c.grey, italic = true, })

    -- Telescope
    hl(0, "TelescopeSelection", { fg = c.blue, })
    hl(0, "TelescopeMatching", { fg = c.yellow, bold = true, })
    hl(0, "TelescopeBorder", { fg = c.blue, bg = c.bg })

    -- NvimTree
    hl(0, "NvimTreeFolderIcon", { fg = c.blue, })
    hl(0, "NvimTreeIndentMarker", { fg = c.light_grey, })
    hl(0, "NvimTreeNormal", { fg = c.dark_grey, bg = c.light_grey })
    hl(0, "NvimTreeVertSplit", { fg = c.alt_bg, bg = c.alt_bg })
    hl(0, "NvimTreeFolderName", { fg = c.blue, })
    hl(0, "NvimTreeOpenedFolderName", { fg = c.blue, bold = true, italic = true, })
    hl(0, "NvimTreeEmptyFolderName", { fg = c.grey, italic = true, })
    hl(0, "NvimTreeGitIgnored", { fg = c.grey, italic = true, })
    hl(0, "NvimTreeImageFile", { fg = c.dark_grey, })
    hl(0, "NvimTreeSpecialFile", { fg = c.orange, })
    hl(0, "NvimTreeEndOfBuffer", { fg = c.light_grey, })
    hl(0, "NvimTreeCursorLine", { bg = c.dark_grey })
    hl(0, "NvimTreeGitignoreIcon", { fg = c.orange, })
    hl(0, "NvimTreeGitStaged", { fg = c.add, })
    hl(0, "NvimTreeGitNew", { fg = c.add, })
    hl(0, "NvimTreeGitRenamed", { fg = c.add, })
    hl(0, "NvimTreeGitDeleted", { fg = c.delete, })
    hl(0, "NvimTreeGitMerge", { fg = c.change, })
    hl(0, "NvimTreeGitDirty", { fg = c.change, })
    hl(0, "NvimTreeSymlink", { fg = c.light_blue, })
    hl(0, "NvimTreeRootFolder", { fg = c.fg, bold = true, })
    hl(0, "NvimTreeExecFile", { fg = c.light_green, })

    -- Buffer
    hl(0, "BufferCurrent", { fg = c.fg, bg = c.bg })
    hl(0, "BufferCurrentIndex", { fg = c.fg, bg = c.bg })
    hl(0, "BufferCurrentMod", { fg = c.yellow, bg = c.bg })
    hl(0, "BufferCurrentSign", { fg = c.blue, bg = c.bg })
    hl(0, "BufferCurrentTarget", { fg = c.red, bg = c.bg, bold = true, })
    hl(0, "BufferVisible", { fg = c.fg, bg = c.bg })
    hl(0, "BufferVisibleIndex", { fg = c.fg, bg = c.bg })
    hl(0, "BufferVisibleMod", { fg = c.yellow, bg = c.bg })
    hl(0, "BufferVisibleSign", { fg = c.grey, bg = c.bg })
    hl(0, "BufferVisibleTarget", { fg = c.red, bg = c.bg, bold = true, })
    hl(0, "BufferInactive", { fg = c.grey, bg = c.alt_bg })
    hl(0, "BufferInactiveIndex", { fg = c.grey, bg = c.alt_bg })
    hl(0, "BufferInactiveMod", { fg = c.yellow, bg = c.alt_bg })
    hl(0, "BufferInactiveSign", { fg = c.grey, bg = c.alt_bg })
    hl(0, "BufferInactiveTarget", { fg = c.red, bg = c.alt_bg, bold = true, })

    -- StatusLine
    hl(0, "StatusLine", { fg = c.light_grey, bg = c.grey })
    hl(0, "StatusLineNC", { fg = c.light_grey, bg = c.grey })
    hl(0, "StatusLineSeparator", { fg = c.light_grey, })
    hl(0, "StatusLineTerm", { fg = c.light_grey, })
    hl(0, "StatusLineTermNC", { fg = c.light_grey, })

    -- IndentBlankline
    hl(0, "IndentBlanklineContextChar", { fg = c.grey, })
    hl(0, "IndentBlanklineContextStart", { underline = true, })
    hl(0, "IndentBlanklineChar", { fg = c.dark_grey, })
    hl(0, "IndentBlanklineSpaceChar", { fg = c.light_blue, })
    hl(0, "IndentBlanklineSpaceCharBlankline", { fg = c.yellow, })

    -- Dashboard
    hl(0, "DashboardCenter", { fg = c.purple, })
    hl(0, "DashboardDesc", { fg = c.grey })
    hl(0, "DashboardFooter", { fg = c.light_blue, })
    hl(0, "DashboardHeader", { fg = c.blue, })
    hl(0, "DashboardIcon", { fg = c.grey, bold = true })
    hl(0, "DashboardKey", { fg = c.orange })
    hl(0, "DashboardShortCut", { fg = c.orange, })

    -- Cmp
    hl(0, "CmpItemAbbrDeprecated", { fg = c.grey, strikethrough = true, })
    hl(0, "CmpItemAbbrMatch", { fg = c.blue, })
    hl(0, "CmpItemAbbrMatchFuzzy", { fg = c.blue, })
    hl(0, "CmpItemKindFunction", { fg = c.blue, })
    hl(0, "CmpItemKindMethod", { fg = c.blue, })
    hl(0, "CmpItemKindConstructor", { fg = c.light_blue, })
    hl(0, "CmpItemKindClass", { fg = c.light_blue, })
    hl(0, "CmpItemKindEnum", { fg = c.light_blue, })
    hl(0, "CmpItemKindEvent", { fg = c.yellow, })
    hl(0, "CmpItemKindInterface", { fg = c.light_blue, })
    hl(0, "CmpItemKindStruct", { fg = c.light_blue, })
    hl(0, "CmpItemKindVariable", { fg = c.red, })
    hl(0, "CmpItemKindField", { fg = c.red, })
    hl(0, "CmpItemKindProperty", { fg = c.red, })
    hl(0, "CmpItemKindEnumMember", { fg = c.orange, })
    hl(0, "CmpItemKindConstant", { fg = c.orange, })
    hl(0, "CmpItemKindKeyword", { fg = c.purple, })
    hl(0, "CmpItemKindModule", { fg = c.light_blue, })
    hl(0, "CmpItemKindValue", { fg = c.fg, })
    hl(0, "CmpItemKindUnit", { fg = c.fg, })
    hl(0, "CmpItemKindText", { fg = c.fg, })
    hl(0, "CmpItemKindSnippet", { fg = c.yellow, })
    hl(0, "CmpItemKindFile", { fg = c.fg, })
    hl(0, "CmpItemKindFolder", { fg = c.fg, })
    hl(0, "CmpItemKindColor", { fg = c.fg, })
    hl(0, "CmpItemKindReference", { fg = c.fg, })
    hl(0, "CmpItemKindOperator", { fg = c.fg, })
    hl(0, "CmpItemKindTypeParameter", { fg = c.red, })
end

return theme
